In [35]:
import pandas as pd
import numpy as np
import os
import pickle

## Load results

In [36]:
with open('results_summary.dict', 'rb') as f:
    stats = pickle.load(f)

## Main tables

In [37]:
def get_latex(df):
    print(df.to_latex().replace('\$', '$'))

In [38]:
def get_results_table(results_dict, metrics, keep_methods):
    d = {}
    missing_methods = []
    for method in keep_methods:
        if method in results_dict:
            # d[method] = ['{:.3f} ({:.3f})'.format(*results_dict[method][metric]) if 'time' in metric else \
            #              '{:.4f} ({:.4f})'.format(*results_dict[method][metric]) for metric in metrics]
            d[method] = ['{:.3f}'.format(*results_dict[method][metric]) if 'time' in metric else \
                         '{:.3f}'.format(*results_dict[method][metric]) for metric in metrics]
        else:
            missing_methods.append(method)
    df = pd.DataFrame.from_dict(d, orient='index')
    df.columns = metrics
    df.index.names = ['alg']
    if len(missing_methods) > 0:
        print('missing methods: {}'.format(missing_methods))
    return df.loc[[x for x in keep_methods if x not in missing_methods]], missing_methods

In [39]:
def get_full_results_table(results_dict, exper_type, num=5):
    metrics = ['test_eval', 
               'test_eq_max', 'test_eq_mean', 
               'test_ineq_max', 'test_ineq_mean',
               'test_time']
    metrics_raw = [x.replace('test_', 'test_raw_') for x in metrics]
    metrics_renaming = ['Obj. value', 
                        'Max eq viol.', 'Mean eq viol.', 
                        'Max ineq viol.', 'Mean ineq viol.',
                        'Time']
    
    nn_methods = ['method', 'method_no_compl', 'method_no_corr', 'method_no_soft', 
               'baseline_nn', 'baseline_eq_nn'] + ['method_deeplde', 'method_pdl', 'method_gauge', 'NN_EqH_Bis']
    opt_methods = dict([
            ('simple', ['osqp', 'qpth']), ('nonconvex', ['ipopt']), ('acopf', ['pypower']), ('qcqp', ['ipopt'])
    ])
    opt_methods_list = ['baseline_opt_{}'.format(x) for x in opt_methods[exper_type]]
    methods_renaming_dict = dict((
            ('method', 'DC3'),
            ('method_no_compl', 'DC3, $\neq$'),
            ('method_no_corr', 'DC3, $\not\leq$ train'),
            ('method_no_corr-noTestCorr', 'DC3, $\not\leq$ train/test'),
            ('method_no_soft', 'DC3, no soft loss'),
            ('baseline_nn-noTestCorr', 'NN'),
            ('baseline_nn', 'NN, $\leq$ test'),
            ('baseline_eq_nn-noTestCorr', 'Eq.~NN'),
            ('baseline_eq_nn', 'Eq.~NN, $\leq$ test'),
            ('baseline_opt_osqp', 'Optimizer (OSQP)'),
            ('baseline_opt_qpth', 'Optimizer (qpth)'),
            ('baseline_opt_ipopt', 'Optimizer (IPOPT)'),
            ('baseline_opt_pypower', 'Optimizer (PYPOWER)'),
            ('method_deeplde', 'DeepLDE'),
            ('method_pdl', 'PDL'),
            ('method_gauge', 'Gauge'),
            ('NN_EqH_Bis', 'NN_EqH_Bis')
        ))
    
    df1, missing_methods = get_results_table(results_dict, metrics, nn_methods + opt_methods_list)
    
    # df2, missing_methods_2 = get_results_table(results_dict, metrics_raw, nn_methods)
    # df2.columns = metrics
    # df2.index =  ['{}-noTestCorr'.format(x) for x in df2.index]
    
    # missing_methods = missing_methods + ['{}-noTestCorr'.format(x) for x in missing_methods_2]
        
    # all_results = pd.concat([df1, df2])
    
    # results_ordering = opt_methods_list + ['method', 'method_no_compl', 'method_no_corr', 'method_no_corr-noTestCorr',
    #                    'method_no_soft', 'baseline_nn-noTestCorr', 'baseline_nn', 'baseline_eq_nn-noTestCorr', 
    #                    'baseline_eq_nn'] + ['method_deeplde' + 'method_pdl', 'method_gauge']
    
    all_results = df1
    results_ordering = opt_methods_list + ['method', 'method_deeplde', 'method_pdl', 'method_gauge', 'NN_EqH_Bis', 'baseline_nn']
    
    all_results = all_results.loc[[x for x in results_ordering if x not in missing_methods]]
    all_results.index = [methods_renaming_dict[x] for x in all_results.index]
    all_results.columns = metrics_renaming
    
    return all_results

In [40]:
df_qcqp_100100 = get_full_results_table(stats['qcqp_ineq100_eq100'], exper_type='qcqp')
df_qcqp_100100

missing methods: ['method', 'method_no_compl', 'method_no_corr', 'method_no_soft', 'baseline_nn', 'baseline_eq_nn', 'method_gauge']

,Obj. value,Max eq viol.,Mean eq viol.,Max ineq viol.,Mean ineq viol.,Time
Optimizer (IPOPT),-11.592,0.000,0.000,0.000,0.000,0.038
DeepLDE,-15.132,0.000,0.000,0.000,0.000,0.002
PDL,-39.088,0.015,0.005,0.005,0.000,0.000
NN_EqH_Bis,-36.182,0.000,0.000,0.000,0.000,0.708

In [41]:
df_qcqp_5050 = get_full_results_table(stats['qcqp_ineq50_eq50'], exper_type='qcqp')
df_qcqp_5050

missing methods: ['method', 'method_no_compl', 'method_no_corr', 'method_no_soft', 'baseline_nn', 'baseline_eq_nn', 'method_gauge']

,Obj. value,Max eq viol.,Mean eq viol.,Max ineq viol.,Mean ineq viol.,Time
Optimizer (IPOPT),-11.592,0.000,0.000,0.000,0.000,0.038
DeepLDE,-10.331,0.000,0.000,0.000,0.000,0.004
PDL,-15.311,0.005,0.002,0.006,0.000,0.000
NN_EqH_Bis,-15.450,0.000,0.000,0.000,0.000,0.694

In [42]:
df_simple_5050 = get_full_results_table(stats['simple_ineq50_eq50'], exper_type='simple')
df_simple_5050

missing methods: ['method_no_compl', 'method_no_corr', 'method_no_soft', 'baseline_eq_nn']

,Obj. value,Max eq viol.,Mean eq viol.,Max ineq viol.,Mean ineq viol.,Time
Optimizer (OSQP),-15.047,0.000,0.000,0.001,0.000,0.001
Optimizer (qpth),-15.047,0.000,0.000,0.000,0.000,1.955
DC3,-12.112,0.000,0.000,0.000,0.000,0.006
DeepLDE,46.316,0.000,0.000,0.007,0.000,0.001
PDL,-14.969,0.011,0.003,0.002,0.000,0.000
Gauge,-13.628,0.000,0.000,0.000,0.000,0.001
NN_EqH_Bis,-11.778,0.000,0.000,0.000,0.000,0.060
"NN, $\leq$ test",-12.545,0.349,0.132,0.000,0.000,0.000

In [43]:
df_simple_100100 = get_full_results_table(stats['simple_ineq100_eq100'], exper_type='simple')
df_simple_100100

missing methods: ['method_no_compl', 'method_no_corr', 'method_no_soft', 'baseline_eq_nn']

,Obj. value,Max eq viol.,Mean eq viol.,Max ineq viol.,Mean ineq viol.,Time
Optimizer (OSQP),-29.176,0.000,0.000,0.000,0.000,0.005
Optimizer (qpth),-29.176,0.000,0.000,0.000,0.000,9.387
DC3,-26.720,0.000,0.000,0.002,0.000,0.012
DeepLDE,-3.697,0.000,0.000,0.000,0.000,0.001
PDL,-28.559,0.421,0.122,0.024,0.000,0.000
Gauge,-28.512,0.000,0.000,0.000,0.000,0.002
NN_EqH_Bis,-23.257,0.000,0.000,0.000,0.000,0.746
"NN, $\leq$ test",-26.786,0.630,0.233,0.000,0.000,0.000

In [44]:
df_nonconvex_5050 = get_full_results_table(stats['nonconvex_ineq50_eq50'], exper_type='nonconvex')
df_nonconvex_5050

missing methods: ['method_no_compl', 'method_no_corr', 'method_no_soft', 'baseline_eq_nn']

,Obj. value,Max eq viol.,Mean eq viol.,Max ineq viol.,Mean ineq viol.,Time
Optimizer (IPOPT),-11.592,0.000,0.000,0.000,0.000,0.038
DC3,-9.718,0.000,0.000,0.000,0.000,0.004
DeepLDE,4.870,0.000,0.000,0.008,0.000,0.001
PDL,-11.385,0.006,0.002,0.001,0.000,0.000
Gauge,-11.296,0.000,0.000,0.000,0.000,0.001
NN_EqH_Bis,-9.616,0.000,0.000,0.000,0.000,0.055
"NN, $\leq$ test",-10.044,0.349,0.133,0.000,0.000,0.012

In [45]:
df_nonconvex_100100 = get_full_results_table(stats['nonconvex_ineq100_eq100'], exper_type='nonconvex')
df_nonconvex_100100

missing methods: ['method_no_compl', 'method_no_corr', 'method_no_soft', 'baseline_eq_nn']

,Obj. value,Max eq viol.,Mean eq viol.,Max ineq viol.,Mean ineq viol.,Time
Optimizer (IPOPT),-22.375,0.000,0.000,0.000,0.000,0.111
DC3,-20.609,0.000,0.000,0.001,0.000,0.009
DeepLDE,-20.074,0.000,0.000,0.000,0.000,0.001
PDL,-21.859,0.589,0.167,0.026,0.000,0.000
Gauge,-21.932,0.000,0.000,0.000,0.000,0.001
NN_EqH_Bis,-19.097,0.000,0.000,0.006,0.000,0.153
"NN, $\leq$ test",-20.736,0.634,0.235,0.000,0.000,0.009

In [46]:
df_qcqp_100100 = get_full_results_table(stats['qcqp_ineq100_eq100'], exper_type='qcqp')
df_qcqp_100100

missing methods: ['method', 'method_no_compl', 'method_no_corr', 'method_no_soft', 'baseline_nn', 'baseline_eq_nn', 'method_gauge']

,Obj. value,Max eq viol.,Mean eq viol.,Max ineq viol.,Mean ineq viol.,Time
Optimizer (IPOPT),-11.592,0.000,0.000,0.000,0.000,0.038
DeepLDE,-15.132,0.000,0.000,0.000,0.000,0.002
PDL,-39.088,0.015,0.005,0.005,0.000,0.000
NN_EqH_Bis,-36.182,0.000,0.000,0.000,0.000,0.708

In [47]:
df_nonconvex_7030 = get_full_results_table(stats['nonconvex_ineq70_eq30'], exper_type='nonconvex')
df_nonconvex_7030

KeyError: 'nonconvex_ineq70_eq30'

In [ ]:
df_acopf = get_full_results_table(stats['acopf'], exper_type='acopf')
df_acopf

KeyError: 'acopf'

## Appendix tables (simple problem)

In [ ]:
def get_comparison_table(all_stats, experiments, metrics, keep_methods):
    d = {}
    for method in keep_methods:
        for metric in metrics:
            d[(method, metric)] = {}
            for experiment in experiments:
                d[(method, metric)][experiment] = '{:.2f} ({:.2f})'.format(*all_stats[experiment][method][metric])
        df = pd.DataFrame.from_dict(d, orient='index')           
    df.index.names = ['Alg', 'Metric']
    return df.iloc[df.index.isin(keep_methods, 'Alg')]

In [ ]:
def get_simple_comparison_table(all_stats, vary_across):
    assert vary_across in ['ineq', 'eq'], 'vary_across should be in [ineq, eq]'
    
    if vary_across == 'ineq':
        experiments = ['simple_ineq10_eq50', 'simple_ineq30_eq50', 'simple_ineq50_eq50', 'simple_ineq70_eq50',
                       'simple_ineq90_eq50']
        experiments_renaming = ['10', '30', '50', '70', '90']
    else:
        experiments = ['simple_ineq50_eq10', 'simple_ineq50_eq30', 'simple_ineq50_eq50', 'simple_ineq50_eq70',
                       'simple_ineq50_eq90']
        experiments_renaming = ['10', '30', '50', '70', '90']
    
    methods = ['method', 'method_no_compl', 'method_no_corr', 'method_no_soft', 
               'baseline_nn', 'baseline_eq_nn', 'baseline_opt_osqp']
    methods_renaming_dict = dict((
            ('method', 'DC3'),
            ('method_no_compl', 'DC3, $\neq$'),
            ('method_no_corr', 'DC3, $\not\leq$ train'),
            ('method_no_corr-noTestCorr', 'DC3, $\not\leq$ train/test'),
            ('method_no_soft', 'DC3, no soft loss'),
            ('baseline_nn-noTestCorr', 'NN'),
            ('baseline_nn', 'NN, $\leq$ test'),
            ('baseline_eq_nn-noTestCorr', 'Eq.~NN'),
            ('baseline_eq_nn', 'Eq.~NN, $\leq$ test'),
            ('baseline_opt_osqp', 'Optimizers (OSQP, qpth)')
        ))
    
    metrics = ['test_eval', 'test_eq_max', 'test_ineq_max']
    metrics_renaming_dict = dict((('test_eval', 'Obj. val.'), ('test_eq_max', 'Max eq.'), ('test_ineq_max', 'Max ineq.')  ))
    clean_metrics = [metrics_renaming_dict[x] for x in metrics]
    metrics_raw = [x.replace('test_', 'test_raw_') if 'time' not in x else x for x in metrics]
    
    df1 = get_comparison_table(all_stats, experiments, metrics, methods)
    df1 = df1.reset_index()
    df1['Metric'] = df1['Metric'].str.replace('_obj_val', '_eval') # make naming consistent
    df1 = df1.set_index(['Alg', 'Metric'])
    
    df2 = get_comparison_table(all_stats, experiments, metrics_raw, methods[:-1])
    df2.columns = experiments
    df2 = df2.reset_index()
    df2['Alg'] = ['{}-noTestCorr'.format(x) for x in df2['Alg']]
    df2['Metric'] = df2['Metric'].str.replace('raw_', '')  # make naming consistent
    df2 = df2.set_index(['Alg', 'Metric'])
    
    all_results = pd.concat([df1, df2])
    results_ordering = ['baseline_opt_osqp', 'method', 'method_no_compl', 'method_no_corr', 'method_no_corr-noTestCorr',
                       'method_no_soft', 'baseline_nn-noTestCorr', 'baseline_nn', 'baseline_eq_nn-noTestCorr', 
                       'baseline_eq_nn']
    clean_results_ordering = [methods_renaming_dict[x] for x in results_ordering]
    all_results = all_results.iloc[all_results.index.isin(results_ordering, 'Alg')]
    all_results = all_results.reindex(pd.MultiIndex.from_product([results_ordering, metrics], names=['Alg', 'Metric']))
    all_results = all_results.reset_index()
    all_results['Alg'] = [methods_renaming_dict[x] for x in all_results['Alg']]
    all_results['Metric'] = [metrics_renaming_dict[x] for x in all_results['Metric']]
    all_results = all_results.set_index(['Alg', 'Metric'])
    all_results.columns = experiments_renaming
    all_results = all_results.reindex(pd.MultiIndex.from_product([clean_results_ordering, clean_metrics])) # remove names
    
    return all_results

In [ ]:
df_simple_varyeq = get_simple_comparison_table(stats, 'eq')
df_simple_varyeq

KeyError: 'simple_ineq50_eq10'

In [ ]:
df_simple_varyineq = get_simple_comparison_table(stats, 'ineq')
df_simple_varyineq

                                                 10             30  \
Optimizers (OSQP, qpth)    Obj. val.  -17.33 (0.00)  -16.33 (0.00)
                           Max eq.      0.00 (0.00)    0.00 (0.00)
                           Max ineq.    0.00 (0.00)    0.00 (0.00)
DC3                        Obj. val.  -15.18 (0.31)  -13.90 (0.20)
                           Max eq.      0.00 (0.00)    0.00 (0.00)
                           Max ineq.    0.00 (0.00)    0.00 (0.00)
DC3, $\neq$                Obj. val.  -15.66 (0.05)  -14.10 (0.04)
                           Max eq.      0.35 (0.00)    0.35 (0.00)
                           Max ineq.    0.00 (0.00)    0.00 (0.00)
DC3, $\not\leq$ train      Obj. val.  -15.60 (0.30)  -13.83 (0.15)
                           Max eq.      0.00 (0.00)    0.00 (0.00)
                           Max ineq.    0.00 (0.00)    0.00 (0.00)
DC3, $\not\leq$ train/test Obj. val.  -15.60 (0.30)  -13.83 (0.15)
                           Max eq.      0.00 (0.00)    0.00 (0.00)
                           Max ineq.    0.00 (0.00)    0.00 (0.00)
DC3, no soft loss          Obj. val.  -21.78 (0.01)  -21.72 (0.03)
                           Max eq.      0.00 (0.00)    0.00 (0.00)
                           Max ineq.   23.85 (0.52)   23.54 (0.23)
NN                         Obj. val.  -15.66 (0.03)  -14.10 (0.05)
                           Max eq.      0.35 (0.00)    0.35 (0.00)
                           Max ineq.    0.00 (0.00)    0.00 (0.00)
NN, $\leq$ test            Obj. val.  -15.66 (0.03)  -14.10 (0.05)
                           Max eq.      0.35 (0.00)    0.35 (0.00)
                           Max ineq.    0.00 (0.00)    0.00 (0.00)
Eq.~NN                     Obj. val.  -17.07 (0.20)  -15.45 (0.09)
                           Max eq.      0.00 (0.00)    0.00 (0.00)
                           Max ineq.    1.65 (0.22)    1.79 (0.10)
Eq.~NN, $\leq$ test        Obj. val.  -17.06 (0.20)  -15.65 (0.09)
                           Max eq.      0.00 (0.00)    0.00 (0.00)
                           Max ineq.    1.53 (0.19)    1.58 (0.08)

                                                 50             70  \
Optimizers (OSQP, qpth)    Obj. val.  -15.05 (0.00)  -14.61 (0.00)
                           Max eq.      0.00 (0.00)    0.00 (0.00)
                           Max ineq.    0.00 (0.00)    0.00 (0.00)
DC3                        Obj. val.  -13.46 (0.01)  -10.52 (0.93)
                           Max eq.      0.00 (0.00)    0.00 (0.00)
                           Max ineq.    0.00 (0.00)    0.00 (0.00)
DC3, $\neq$                Obj. val.  -12.58 (0.04)  -12.10 (0.03)
                           Max eq.      0.35 (0.00)    0.35 (0.00)
                           Max ineq.    0.00 (0.00)    0.00 (0.00)
DC3, $\not\leq$ train      Obj. val.   -1.39 (0.97)  -11.14 (0.05)
                           Max eq.      0.00 (0.00)    0.00 (0.00)
                           Max ineq.    0.02 (0.02)    0.00 (0.00)
DC3, $\not\leq$ train/test Obj. val.   -1.23 (1.21)  -11.14 (0.05)
                           Max eq.      0.00 (0.00)    0.00 (0.00)
                           Max ineq.    0.09 (0.13)    0.00 (0.00)
DC3, no soft loss          Obj. val.  -21.84 (0.00)  -21.82 (0.01)
                           Max eq.      0.00 (0.00)    0.00 (0.00)
                           Max ineq.   23.83 (0.11)   23.73 (0.09)
NN                         Obj. val.  -12.57 (0.01)  -12.12 (0.03)
                           Max eq.      0.35 (0.00)    0.35 (0.00)
                           Max ineq.    0.00 (0.00)    0.00 (0.00)
NN, $\leq$ test            Obj. val.  -12.57 (0.01)  -12.12 (0.03)
                           Max eq.      0.35 (0.00)    0.35 (0.00)
                           Max ineq.    0.00 (0.00)    0.00 (0.00)
Eq.~NN                     Obj. val.   -9.16 (0.75)  -14.20 (0.06)
                           Max eq.      0.00 (0.00)    0.00 (0.00)
                           Max ineq.    8.83 (0.72)    2.26 (0.04)
Eq.~NN, $\leq$ test        Obj. val.  -14.68 (0.05)  -14.31 (0.06)
                           Max eq.      0.00 (0.00)    0.00 (0.00)
                           Max ineq.    0.89 (0.05)    1.92 (0.04)

                                                 90
Optimizers (OSQP, qpth)    Obj. val.  -14.26 (0.00)
                           Max eq.      0.00 (0.00)
                           Max ineq.    0.00 (0.00)
DC3                        Obj. val.  -11.77 (0.07)
                           Max eq.      0.00 (0.00)
                           Max ineq.    0.00 (0.00)
DC3, $\neq$                Obj. val.  -11.72 (0.03)
                           Max eq.      0.35 (0.00)
                           Max ineq.    0.00 (0.00)
DC3, $\not\leq$ train      Obj. val.  -11.76 (0.06)
                           Max eq.      0.00 (0.00)
                           Max ineq.    0.00 (0.00)
DC3, $\not\leq$ train/test Obj. val.  -11.76 (0.06)
                           Max eq.      0.00 (0.00)
                           Max ineq.    0.00 (0.00)
DC3, no soft loss          Obj. val.  -21.83 (0.00)
                           Max eq.      0.00 (0.00)
                           Max ineq.   23.69 (0.06)
NN                         Obj. val.  -11.70 (0.02)
                           Max eq.      0.35 (0.00)
                           Max ineq.    0.00 (0.00)
NN, $\leq$ test            Obj. val.  -11.70 (0.02)
                           Max eq.      0.35 (0.00)
                           Max ineq.    0.00 (0.00)
Eq.~NN                     Obj. val.  -14.10 (0.10)
                           Max eq.      0.00 (0.00)
                           Max ineq.    1.28 (0.05)
Eq.~NN, $\leq$ test        Obj. val.  -14.10 (0.10)
                           Max eq.      0.00 (0.00)
                           Max ineq.    1.25 (0.04)

## LaTeX

In [ ]:
get_latex(df_simple_5050)

\begin{tabular}{lllllll}
\toprule
{} &         Obj. value &     Max eq viol. &    Mean eq viol. &   Max ineq viol. &  Mean ineq viol. &           Time \\
\midrule
Optimizer (OSQP) &  -15.0470 (0.0000) &  0.0001 (0.0000) &  0.0001 (0.0000) &  0.0005 (0.0000) &  0.0000 (0.0000) &  0.001 (0.000) \\
Optimizer (qpth) &  -15.0469 (0.0000) &  0.0000 (0.0000) &  0.0000 (0.0000) &  0.0000 (0.0000) &  0.0000 (0.0000) &  1.955 (0.000) \\
DC3              &  -12.1118 (0.0000) &  0.0000 (0.0000) &  0.0000 (0.0000) &  0.0005 (0.0000) &  0.0000 (0.0000) &  0.006 (0.000) \\
DeepLDE          &   46.3161 (0.0000) &  0.0000 (0.0000) &  0.0000 (0.0000) &  0.0068 (0.0000) &  0.0001 (0.0000) &  0.001 (0.000) \\
PDL              &  -14.9687 (0.0000) &  0.0111 (0.0000) &  0.0034 (0.0000) &  0.0021 (0.0000) &  0.0001 (0.0000) &  0.000 (0.000) \\
Gauge            &  -13.6279 (0.0000) &  0.0000 (0.0000) &  0.0000 (0.0000) &  0.0000 (0.0000) &  0.0000 (0.0000) &  0.001 (0.000) \\
\bottomrule
\end{tabular}

/tmp/ipykernel_4192783/761946459.py:2: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(df.to_latex().replace('\$', '$'))

In [ ]:
get_latex(df_nonconvex)

In [ ]:
get_latex(df_acopf)

In [ ]:
get_latex(df_simple_varyeq)

In [ ]:
get_latex(df_simple_varyineq)

In [ ]:
get_latex(df_simple_100100)

\begin{tabular}{lllllll}
\toprule
{} & Obj. value & Max eq viol. & Mean eq viol. & Max ineq viol. & Mean ineq viol. &   Time \\
\midrule
Optimizer (OSQP) &    -29.176 &        0.000 &         0.000 &          0.000 &           0.000 &  0.005 \\
Optimizer (qpth) &    -29.176 &        0.000 &         0.000 &          0.000 &           0.000 &  9.387 \\
DC3              &    -26.720 &        0.000 &         0.000 &          0.002 &           0.000 &  0.012 \\
DeepLDE          &     -3.697 &        0.000 &         0.000 &          0.000 &           0.000 &  0.001 \\
PDL              &    -28.559 &        0.421 &         0.122 &          0.024 &           0.000 &  0.000 \\
Gauge            &    -28.512 &        0.000 &         0.000 &          0.000 &           0.000 &  0.002 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_4193607/761946459.py:2: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(df.to_latex().replace('\$', '$'))

In [ ]:
get_latex(df_simple_5050)

\begin{tabular}{lllllll}
\toprule
{} & Obj. value & Max eq viol. & Mean eq viol. & Max ineq viol. & Mean ineq viol. &   Time \\
\midrule
Optimizer (OSQP) &    -15.047 &        0.000 &         0.000 &          0.001 &           0.000 &  0.001 \\
Optimizer (qpth) &    -15.047 &        0.000 &         0.000 &          0.000 &           0.000 &  1.955 \\
DC3              &    -12.112 &        0.000 &         0.000 &          0.000 &           0.000 &  0.006 \\
DeepLDE          &     46.316 &        0.000 &         0.000 &          0.007 &           0.000 &  0.001 \\
PDL              &    -14.969 &        0.011 &         0.003 &          0.002 &           0.000 &  0.000 \\
Gauge            &    -13.628 &        0.000 &         0.000 &          0.000 &           0.000 &  0.001 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_4193607/761946459.py:2: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(df.to_latex().replace('\$', '$'))

In [ ]:
get_latex(df_nonconvex_100100)

\begin{tabular}{lllllll}
\toprule
{} & Obj. value & Max eq viol. & Mean eq viol. & Max ineq viol. & Mean ineq viol. &   Time \\
\midrule
Optimizer (IPOPT) &    -22.375 &        0.000 &         0.000 &          0.000 &           0.000 &  0.111 \\
DC3               &    -20.609 &        0.000 &         0.000 &          0.001 &           0.000 &  0.009 \\
DeepLDE           &    -20.074 &        0.000 &         0.000 &          0.000 &           0.000 &  0.001 \\
PDL               &    -21.859 &        0.589 &         0.167 &          0.026 &           0.000 &  0.000 \\
Gauge             &    -21.932 &        0.000 &         0.000 &          0.000 &           0.000 &  0.001 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_4193607/761946459.py:2: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(df.to_latex().replace('\$', '$'))

In [ ]:
get_latex(df_nonconvex_5050)

\begin{tabular}{lllllll}
\toprule
{} & Obj. value & Max eq viol. & Mean eq viol. & Max ineq viol. & Mean ineq viol. &   Time \\
\midrule
Optimizer (IPOPT) &    -11.592 &        0.000 &         0.000 &          0.000 &           0.000 &  0.038 \\
DC3               &     -9.718 &        0.000 &         0.000 &          0.000 &           0.000 &  0.004 \\
DeepLDE           &      4.870 &        0.000 &         0.000 &          0.008 &           0.000 &  0.001 \\
PDL               &    -11.385 &        0.006 &         0.002 &          0.001 &           0.000 &  0.000 \\
Gauge             &    -11.296 &        0.000 &         0.000 &          0.000 &           0.000 &  0.001 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_4193607/761946459.py:2: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(df.to_latex().replace('\$', '$'))